artifact_uri: /home/emmanuel/Documents/GitHub/PRE-08-mlflow-tracking-local-EmmanuelCuartasG/my_mlruns/110809152811556666/ca0324ff15d643cd927eb4631eb8ddde/artifacts
end_time: 1748099791959
entry_point_name: ''
experiment_id: '110809152811556666'
lifecycle_stage: active
run_id: ca0324ff15d643cd927eb4631eb8ddde
run_name: knn_44da4b80
run_uuid: ca0324ff15d643cd927eb4631eb8ddde
source_name: ''
source_type: 4
source_version: ''
start_time: 1748099791939
status: 3
tags: []
user_id: emmanuel
